name: Test and Deploy

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Train
        run: parserator train training/labeled.xml,training/cities.xml,training/hwys_and_srs.xml,training/numeric_road_names.xml,training/units.xml usaddress

      - name: Test
        run: nosetests --with-coverage --cover-package=usaddress

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build
        run: |
          pip install build --user
          python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
